// <auto-generated />
using System;
using CinemaTickets.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaTickets.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705113144_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaTickets.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Academy Award-winning actor.",
                            Name = "Tom Hanks"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Hollywood A-list actress.",
                            Name = "Scarlett Johansson"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Oscar-winning actor.",
                            Name = "Leonardo DiCaprio"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Hunger Games star.",
                            Name = "Jennifer Lawrence"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Iron Man himself.",
                            Name = "Robert Downey Jr."
                        });
                });

            modelBuilder.Entity("CinemaTickets.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sci-Fi"
                        });
                });

            modelBuilder.Entity("CinemaTickets.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Downtown",
                            Name = "Grand Cinema"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Westside",
                            Name = "Star Cinema"
                        },
                        new
                        {
                            Id = 3,
                            Location = "North Mall",
                            Name = "Galaxy Cinema"
                        });
                });

            modelBuilder.Entity("CinemaTickets.Models.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CinemaId = 1,
                            Description = "Main IMAX Screen",
                            Name = "Screen 1",
                            TotalSeats = 200
                        },
                        new
                        {
                            Id = 2,
                            CinemaId = 1,
                            Description = "Standard Hall",
                            Name = "Screen 2",
                            TotalSeats = 150
                        },
                        new
                        {
                            Id = 3,
                            CinemaId = 2,
                            Description = "Dolby Atmos",
                            Name = "Hall A",
                            TotalSeats = 180
                        },
                        new
                        {
                            Id = 4,
                            CinemaId = 2,
                            Description = "Premium Seating",
                            Name = "VIP Room",
                            TotalSeats = 60
                        },
                        new
                        {
                            Id = 5,
                            CinemaId = 3,
                            Description = "4DX Experience",
                            Name = "Hall 1",
                            TotalSeats = 220
                        });
                });

            modelBuilder.Entity("CinemaTickets.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("HallId")
                        .HasColumnType("int");

                    b.Property<string>("MainImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CinemaId");

                    b.HasIndex("HallId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 145,
                            CategoryId = 5,
                            CinemaId = 1,
                            CreatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateTime = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An epic sci-fi adventure across the cosmos where humanity battles an alien empire.",
                            HallId = 1,
                            Name = "Galactic Warriors",
                            Price = 12.99m,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 180,
                            CategoryId = 2,
                            CinemaId = 2,
                            CreatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateTime = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A heartwarming romance between two strangers in the City of Light.",
                            HallId = 3,
                            Name = "Love in Paris",
                            Price = 9.99m,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 0,
                            CategoryId = 4,
                            CinemaId = 3,
                            CreatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateTime = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A chilling horror mystery set in an isolated mansion.",
                            HallId = 5,
                            Name = "The Dark Secret",
                            Price = 11.50m,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 55,
                            CategoryId = 3,
                            CinemaId = 1,
                            CreatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateTime = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A hilarious comedy following three mismatched roommates in New York City.",
                            HallId = 2,
                            Name = "Laughing Out Loud",
                            Price = 8.99m,
                            Status = 1
                        });
                });

            modelBuilder.Entity("CinemaTickets.Models.MovieActor", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 1,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 4
                        });
                });

            modelBuilder.Entity("CinemaTickets.Models.MovieSubImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieSubImages");
                });

            modelBuilder.Entity("CinemaTickets.Models.Hall", b =>
                {
                    b.HasOne("CinemaTickets.Models.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("CinemaTickets.Models.Movie", b =>
                {
                    b.HasOne("CinemaTickets.Models.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaTickets.Models.Cinema", "Cinema")
                        .WithMany("Movies")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaTickets.Models.Hall", "Hall")
                        .WithMany("Movies")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Cinema");

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("CinemaTickets.Models.MovieActor", b =>
                {
                    b.HasOne("CinemaTickets.Models.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaTickets.Models.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaTickets.Models.MovieSubImage", b =>
                {
                    b.HasOne("CinemaTickets.Models.Movie", "Movie")
                        .WithMany("SubImages")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaTickets.Models.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("CinemaTickets.Models.Category", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("CinemaTickets.Models.Cinema", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("CinemaTickets.Models.Hall", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("CinemaTickets.Models.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("SubImages");
                });
#pragma warning restore 612, 618
        }
    }
}
